export * from './validatorComposite'
export * from './validatorInputRequired'
export * from './validatorCompareInputs'
export * from './validatorEmail'
export * from '@/validations/protocols/validator'
export * from '@/validations/protocols/emailValidator'
